version: '3.5'
services: # Here we define our service(s)
  postgres:
    image: postgres
    hostname: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=pizza-moberries
      - POSTGRES_USER=krythor
      - POSTGRES_PASSWORD=root
  pizza-api-service: # The name of the service
    container_name: pizza-api  # Container name
    build: ./app # Location of our Dockerfile
    volumes: # Volume binding
      - './app:/usr/src/app' 
    ports: 
      - '8005:8005' # Port mapping
    depends_on:
      - postgres
    command: 
      sh -c "/wait && cd /usr/src/app && python manage.py migrate && python manage.py runserver 0.0.0.0:8005"
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30