# Generated by Django 3.1.3 on 2020-11-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_queue', 'In Queue'), ('in_production', 'In Production'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered')], default='in_queue', max_length=15, verbose_name='Status')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pizzas', models.ManyToManyField(related_name='order_pizzas', to='pizzasApp.Pizza')),
            ],
        ),
    ]
