# Generated by Django 3.1.3 on 2020-11-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApp', '0002_auto_20201121_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_queue', 'In Queue'), ('in_production', 'In Production'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered')], default='in_queue', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
