# Generated by Django 3.1.3 on 2020-11-22 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientsApp', '0001_initial'),
        ('ordersApp', '0003_auto_20201122_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientsApp.client'),
            preserve_default=False,
        ),
    ]
