# Generated by Django 3.1.3 on 2020-11-21 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flavorsApp', '0001_initial'),
        ('sizesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flavorsApp.flavor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizesApp.size')),
            ],
        ),
    ]
